# Generated by Django 2.2.5 on 2020-08-06 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200805_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(blank=True, choices=[('email', 'Email'), ('github', 'Github'), ('kakao', 'Kakao')], max_length=10),
        ),
    ]
