# Generated by Django 2.2.5 on 2020-07-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_auto_20200713_1701'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='amenity',
            new_name='amenities',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='facility',
            new_name='facilities',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='house_rule',
            new_name='house_rules',
        ),
    ]
