# Generated by Django 2.2.5 on 2020-07-22 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20200717_1944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='baths',
            new_name='bathrooms',
        ),
    ]
