# Generated by Django 2.2.5 on 2020-08-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_auto_20200722_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='guest',
            field=models.IntegerField(help_text='How many people will be staying?'),
        ),
    ]
